# Generated by Django 4.0.1 on 2022-01-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlavorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
